# Generated by Django 4.2.7 on 2023-12-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userextended_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('message', models.TextField(blank=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
