# Generated by Django 4.2.7 on 2023-12-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_link', models.URLField(blank=True, null=True)),
                ('grade_level', models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2')], max_length=5)),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Video'), ('DOC', 'Document'), ('QUIZ', 'Quiz')], max_length=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
